# Generated by Django 5.0.1 on 2024-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='copies',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='xerox_type',
            field=models.CharField(default='Single Side', max_length=100, null=True),
        ),
    ]
